#chrome , firefox, msedge
browserName= chrome
Envrionment = stg
stg=https://www.thewildest-stg.com/
UAT= https://demowebshop.tricentis.com/
prod= https://demowebshop.tricentis.com/
cityname = Mumbai
Food = Drinks
email= obsqura24@gmail.com
Emailid=wildest123@gmail.com
passwrd=password@123
password= mypassword
Resister=Your registration completed
subscriptionMsg= Thank you for signing up! A verification email has been sent. We appreciate your interest.